# Generated by Django 4.1 on 2024-02-22 07:08

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyCoding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('img_size', models.IntegerField(choices=[(50, '50%'), (40, '40%'), (70, '70%'), (100, '100%'), (30, '30%')])),
                ('content_body', markdownx.models.MarkdownxField()),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('regist_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'py_coding',
            },
        ),
    ]
