# Generated by Django 4.1 on 2024-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycoding',
            name='img_size',
            field=models.IntegerField(choices=[(40, '40%'), (50, '50%'), (70, '70%'), (100, '100%'), (30, '30%')]),
        ),
    ]
