# Generated by Django 4.1 on 2024-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_alter_pycoding_img_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycoding',
            name='regist_dt',
            field=models.DateTimeField(),
        ),
    ]
