# Generated by Django 4.1 on 2024-02-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_alter_pycoding_regist_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycoding',
            name='use_yn',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
