# Generated by Django 4.1 on 2024-02-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0022_alter_pycoding_img_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycoding',
            name='img_size',
            field=models.IntegerField(choices=[(50, '50%'), (100, '100%'), (30, '30%'), (40, '40%'), (70, '70%')]),
        ),
        migrations.AlterField(
            model_name='pycoding',
            name='regist_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
