# Generated by Django 4.1 on 2024-02-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('regist_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'py_blog',
            },
        ),
        migrations.CreateModel(
            name='PyBlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('img_size', models.CharField(blank=True, max_length=3, null=True)),
                ('content_body', models.TextField(blank=True, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pb_detail', to='blog.pyblog')),
            ],
            options={
                'db_table': 'py_blog_detail',
                'managed': True,
            },
        ),
    ]
