# Generated by Django 4.1 on 2024-02-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_pyblog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyBlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('img_size', models.CharField(blank=True, max_length=3, null=True)),
                ('content_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'py_blog_detail',
                'managed': False,
            },
        ),
    ]
