# Generated by Django 4.1 on 2024-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pyblogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyblog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
