# Generated by Django 4.1 on 2024-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pyblog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
